# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screen2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtCore import QPropertyAnimation


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(627, 383)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_superior = QtWidgets.QFrame(Form)
        self.frame_superior.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_superior.setStyleSheet("background-color:rgb(85, 255, 255)")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bt_menu = QtWidgets.QPushButton(self.frame_superior)
        self.bt_menu.setMinimumSize(QtCore.QSize(140, 30))
        self.bt_menu.setStyleSheet("QPushButton:hover{\n"
"background-color: white;\n"
"font: 87 8pt \"Arial Black\"\n"
"}\n"
"\n"
"QPushButton{\n"
"border:0px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/icons/icons/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_menu.setIcon(icon)
        self.bt_menu.setObjectName("bt_menu")
        self.bt_menu.clicked.connect(self.mover_menu)

        self.horizontalLayout_4.addWidget(self.bt_menu)
        spacerItem = QtWidgets.QSpacerItem(225, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.frame_superior)
        self.frame_inferior = QtWidgets.QFrame(Form)
        self.frame_inferior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_inferior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_inferior.setObjectName("frame_inferior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_inferior)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_lateral = QtWidgets.QFrame(self.frame_inferior)
        self.frame_lateral.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_lateral.setMaximumSize(QtCore.QSize(0, 16777215))
        self.frame_lateral.setStyleSheet("QFrame{\n"
"background: rgb(85, 170, 255)\n"
"}\n"
"\n"
"QPushButton{\n"
"border-top-left-radius: 20px; \n"
"border-bottom-left-radius: 20px;\n"
"}\n"
"\n"
"QPushButton-hover{\n"
"background-color: white; \n"
"border-top-left-radius: 20px; \n"
"border-bottom-left-radius: 20px; \n"
"}\n"
"")
        self.frame_lateral.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_lateral.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_lateral.setObjectName("frame_lateral")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_lateral)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bt_path = QtWidgets.QPushButton(self.frame_lateral)
        self.bt_path.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_path.setStyleSheet("QPushButton:hover{\n"
"background-color:white;\n"
"}")
        self.bt_path.setObjectName("bt_path")
        self.verticalLayout_2.addWidget(self.bt_path)
        self.bt_general = QtWidgets.QPushButton(self.frame_lateral)
        self.bt_general.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_general.setStyleSheet("QPushButton:hover{\n"
"background-color:white;\n"
"}\n"
"")
        self.bt_general.setObjectName("bt_general")
        self.verticalLayout_2.addWidget(self.bt_general)
        self.bt_advanced = QtWidgets.QPushButton(self.frame_lateral)
        self.bt_advanced.setMinimumSize(QtCore.QSize(0, 40))
        self.bt_advanced.setStyleSheet("QPushButton:hover{\n"
"background-color:white;\n"
"}")
        self.bt_advanced.setObjectName("bt_advanced")
        self.verticalLayout_2.addWidget(self.bt_advanced)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.frame_lateral)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout.addWidget(self.frame_lateral)
        self.frame = QtWidgets.QFrame(self.frame_inferior)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.page)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_4.addWidget(self.pushButton_3)
        self.stackedWidget.addWidget(self.page)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.generalInfo = QtWidgets.QPushButton(self.page_1)
        self.generalInfo.setObjectName("generalInfo")

        self.generalInfo.clicked.connect(self.getFileName)

        self.verticalLayout_6.addWidget(self.generalInfo)
        self.bookLabel = QtWidgets.QLabel(self.page_1)
        self.bookLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.bookLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bookLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.bookLabel.setObjectName("bookLabel")
        self.verticalLayout_6.addWidget(self.bookLabel)
        self.pushButton = QtWidgets.QPushButton(self.page_1)
        self.pushButton.setObjectName("pushButton")

        self.pushButton.clicked.connect(self.getFileName2)


        self.verticalLayout_6.addWidget(self.pushButton)
        self.sampleLabel = QtWidgets.QLabel(self.page_1)
        self.sampleLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.sampleLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sampleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sampleLabel.setObjectName("sampleLabel")
        self.verticalLayout_6.addWidget(self.sampleLabel)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.generalPa = QtWidgets.QPushButton(self.page_2)
        self.generalPa.setObjectName("generalPa")
        self.verticalLayout_5.addWidget(self.generalPa)
        self.FirstPageLabel = QtWidgets.QLabel(self.page_2)
        self.FirstPageLabel.setObjectName("FirstPageLabel")
        self.verticalLayout_5.addWidget(self.FirstPageLabel)
        self.FirstPagespinBox = QtWidgets.QSpinBox(self.page_2)
        self.FirstPagespinBox.setObjectName("FirstPagespinBox")
        self.verticalLayout_5.addWidget(self.FirstPagespinBox)
        self.LastPageLabel = QtWidgets.QLabel(self.page_2)
        self.LastPageLabel.setObjectName("LastPageLabel")
        self.verticalLayout_5.addWidget(self.LastPageLabel)
        self.SecondPageSpinBox = QtWidgets.QSpinBox(self.page_2)
        self.SecondPageSpinBox.setObjectName("SecondPageSpinBox")
        self.verticalLayout_5.addWidget(self.SecondPageSpinBox)
        self.SamplingPageLabel = QtWidgets.QLabel(self.page_2)
        self.SamplingPageLabel.setObjectName("SamplingPageLabel")
        self.verticalLayout_5.addWidget(self.SamplingPageLabel)
        self.SamplingcomboBox = QtWidgets.QComboBox(self.page_2)
        self.SamplingcomboBox.setObjectName("SamplingcomboBox")
        self.SamplingcomboBox.addItem("")
        self.SamplingcomboBox.addItem("")
        self.verticalLayout_5.addWidget(self.SamplingcomboBox)
        self.ThresholdingImageLabel = QtWidgets.QLabel(self.page_2)
        self.ThresholdingImageLabel.setObjectName("ThresholdingImageLabel")
        self.verticalLayout_5.addWidget(self.ThresholdingImageLabel)
        self.ThresholdingImagecomboBox = QtWidgets.QComboBox(self.page_2)
        self.ThresholdingImagecomboBox.setObjectName("ThresholdingImagecomboBox")
        self.ThresholdingImagecomboBox.addItem("")
        self.ThresholdingImagecomboBox.addItem("")
        self.verticalLayout_5.addWidget(self.ThresholdingImagecomboBox)
        self.ResizingImageLabel = QtWidgets.QLabel(self.page_2)
        self.ResizingImageLabel.setObjectName("ResizingImageLabel")
        self.verticalLayout_5.addWidget(self.ResizingImageLabel)
        self.ResizingImagecomboBox = QtWidgets.QComboBox(self.page_2)
        self.ResizingImagecomboBox.setObjectName("ResizingImagecomboBox")
        self.ResizingImagecomboBox.addItem("")
        self.ResizingImagecomboBox.addItem("")
        self.verticalLayout_5.addWidget(self.ResizingImagecomboBox)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.advancedPa = QtWidgets.QPushButton(self.page_3)
        self.advancedPa.setObjectName("advancedPa")
        self.verticalLayout_3.addWidget(self.advancedPa)
        self.ThresoldinMethodLabel = QtWidgets.QLabel(self.page_3)
        self.ThresoldinMethodLabel.setObjectName("ThresoldinMethodLabel")
        self.verticalLayout_3.addWidget(self.ThresoldinMethodLabel)
        self.ThresholdingMethodComboBox = QtWidgets.QComboBox(self.page_3)
        self.ThresholdingMethodComboBox.setObjectName("ThresholdingMethodComboBox")
        self.ThresholdingMethodComboBox.addItem("")
        self.ThresholdingMethodComboBox.addItem("")
        self.ThresholdingMethodComboBox.addItem("")
        self.ThresholdingMethodComboBox.addItem("")
        self.ThresholdingMethodComboBox.addItem("")
        self.ThresholdingMethodComboBox.addItem("")
        self.ThresholdingMethodComboBox.addItem("")
        self.ThresholdingMethodComboBox.addItem("")
        self.ThresholdingMethodComboBox.addItem("")
        self.verticalLayout_3.addWidget(self.ThresholdingMethodComboBox)
        self.ResizingMethodLabel = QtWidgets.QLabel(self.page_3)
        self.ResizingMethodLabel.setObjectName("ResizingMethodLabel")
        self.verticalLayout_3.addWidget(self.ResizingMethodLabel)
        self.ResizingMethodComboBox = QtWidgets.QComboBox(self.page_3)
        self.ResizingMethodComboBox.setObjectName("ResizingMethodComboBox")
        self.ResizingMethodComboBox.addItem("")
        self.ResizingMethodComboBox.addItem("")
        self.ResizingMethodComboBox.addItem("")
        self.ResizingMethodComboBox.addItem("")
        self.ResizingMethodComboBox.addItem("")
        self.verticalLayout_3.addWidget(self.ResizingMethodComboBox)

        self.stackedWidget.addWidget(self.page_3)
        self.horizontalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout.addWidget(self.frame_inferior)
        self.exit = QtWidgets.QPushButton(Form)
        self.exit.setObjectName("exit")
        self.verticalLayout.addWidget(self.exit)

        self.bt_path.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.page_1))
        self.bt_general.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.page_2))
        self.bt_advanced.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.page_3))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.bt_menu.setText(_translate("Form", "MENU"))
        self.bt_path.setText(_translate("Form", "Info"))
        self.bt_general.setText(_translate("Form", "General Param"))
        self.bt_advanced.setText(_translate("Form", "Advanced Param"))
        self.label.setText(_translate("Form", "Python-Scan"))
        self.pushButton_3.setText(_translate("Form", "PushButton"))
        self.generalInfo.setText(_translate("Form", "Book file (.pdf)"))
        self.bookLabel.setText(_translate("Form", "None Selected"))
        self.pushButton.setText(_translate("Form", "Sample File (.txt)"))
        self.sampleLabel.setText(_translate("Form", "None Selected"))
        self.generalPa.setText(_translate("Form", "General"))
        self.FirstPageLabel.setText(_translate("Form", "First Page"))
        self.LastPageLabel.setText(_translate("Form", "Last Page"))
        self.SamplingPageLabel.setText(_translate("Form", "Sampling"))
        self.SamplingcomboBox.setItemText(0, _translate("Form", "True"))
        self.SamplingcomboBox.setItemText(1, _translate("Form", "False"))
        self.ThresholdingImageLabel.setText(_translate("Form", "Thresholding Image"))
        self.ThresholdingImagecomboBox.setItemText(0, _translate("Form", "True"))
        self.ThresholdingImagecomboBox.setItemText(1, _translate("Form", "False"))
        self.ResizingImageLabel.setText(_translate("Form", "Resizing Image"))
        self.ResizingImagecomboBox.setItemText(0, _translate("Form", "True"))
        self.ResizingImagecomboBox.setItemText(1, _translate("Form", "False"))
        self.advancedPa.setText(_translate("Form", "Advanced Parameters"))
        self.ThresoldinMethodLabel.setText(_translate("Form", "Thresholding Method"))
        self.ThresholdingMethodComboBox.setItemText(0, _translate("Form", "None"))
        self.ThresholdingMethodComboBox.setItemText(1, _translate("Form", "All"))
        self.ThresholdingMethodComboBox.setItemText(2, _translate("Form", "1"))
        self.ThresholdingMethodComboBox.setItemText(3, _translate("Form", "2"))
        self.ThresholdingMethodComboBox.setItemText(4, _translate("Form", "3"))
        self.ThresholdingMethodComboBox.setItemText(5, _translate("Form", "4"))
        self.ThresholdingMethodComboBox.setItemText(6, _translate("Form", "5"))
        self.ThresholdingMethodComboBox.setItemText(7, _translate("Form", "6"))
        self.ThresholdingMethodComboBox.setItemText(8, _translate("Form", "7"))
        self.ResizingMethodLabel.setText(_translate("Form", "Resizing Method"))
        self.ResizingMethodComboBox.setItemText(0, _translate("Form", "None"))
        self.ResizingMethodComboBox.setItemText(1, _translate("Form", "All"))
        self.ResizingMethodComboBox.setItemText(2, _translate("Form", "1"))
        self.ResizingMethodComboBox.setItemText(3, _translate("Form", "2"))
        self.ResizingMethodComboBox.setItemText(4, _translate("Form", "3"))
        self.exit.setText(_translate("Form", "Exit"))
        self.exit.clicked.connect(lambda: self.closescr(Form))

    def mover_menu(self):
        if True:
            width = self.frame_lateral.width()
            normal = 0
            if width == 0:
                extender = 200
            else:
                extender = normal
            self.animacion = QPropertyAnimation(self.frame_lateral, b'minimumWidth')
            self.animacion.setDuration(300)
            self.animacion.setStartValue(width)
            self.animacion.setEndValue(extender)
            self.animacion.setEasingCurve(QtCore.QEasingCurve.InOutQuart)
            self.animacion.start()

    def closescr(self, Form):
        print(self.FirstPagespinBox.value())
        Form.hide()

    def getFileName(self):
        response = QFileDialog.getOpenFileName(
        )
        print(response)
        self.bookLabel.setText(response[0])
        return response[0]

    def getFileName2(self):
        response = QFileDialog.getOpenFileName(
        )
        print(response)
        self.sampleLabel.setText(response[0])
        return response[0]


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

