# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testing_table.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys, os
sys.path.append(os.path.abspath(os.path.join('..')))
from Scan import Scan
from PyQt5 import QtCore, QtGui, QtWidgets
import pandas as pd
from PyQt5.QtCore import QAbstractTableModel, Qt
from PyQt5.QtWidgets import QApplication, QTableView
import time
from PyQt5.QtCore import QObject, QThread, pyqtSignal
from time import sleep
from PyQt5.QtWidgets import QLabel, QHeaderView
import json
import os
import copy

NUM_THRESHOLDING_METHOD_OPTIONS = 7
NUM_RESIZING_METHOD_OPTIONS = 3


class Ui_Screen3(object):

    def __init__(self, dict_parameters):
        self.dict_parameters = dict_parameters
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(977, 671)

        self.thread={}
        self.n = 1
        self.df = pd.DataFrame()


        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(790, 140, 91, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.runLongTask)

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(790, 240, 91, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.refresh)

        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(40, 60, 721, 461))
        self.tableView.setObjectName("tableView")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(790, 380, 131, 91))
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(790, 470, 120, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 977, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def reportProgress(self, n, n_total):
        self.progressBar.setMinimum(0)
        self.progressBar.setMaximum(n_total)
        self.progressBar.setValue(n + 1)
        self.label.setText(f"Long-Running Step: {n} out of {n_total}")
        self.label.adjustSize()



    class Worker(QObject):

        def __init__(self, dict_parameters):
            QObject.__init__(self)
            self.dict_parameters = dict_parameters
        finished = pyqtSignal()
        progress = pyqtSignal(int, int)

        def run(self):
            # self.dict_parameters = {
            #     'Paths': {'BookFile': 'C:/Users/Hp/PycharmProjects/ImageToTextArgentina/data/libro_1.pdf',
            #               'SampleFile': 'C:/Users/Hp/PycharmProjects/ImageToTextArgentina/data/libro_1_sample.txt'},
            #     'GeneralParameters': {'FirstPage': 20, 'LastPage': 21, 'Sampling': 0, 'ThresholdingImage': True,
            #                           'ResizingImage': True},
            #     'AdvancedParameters': {'ThresholdingMethod': 'All', 'ResizingMethod': 'All'}}

            self.dict_parameters_list = []

            if self.dict_parameters['AdvancedParameters']['ThresholdingMethod'] == 'All' and not \
                    self.dict_parameters['AdvancedParameters']['ResizingMethod'] == 'All':
                for num in range(1, NUM_THRESHOLDING_METHOD_OPTIONS + 1):
                    self.dict_parameters_list.append(copy.deepcopy(self.dict_parameters))
                    self.dict_parameters_list[num - 1]['AdvancedParameters']['ThresholdingMethod'] = num

            if self.dict_parameters['AdvancedParameters']['ResizingMethod'] == 'All' and not \
            self.dict_parameters['AdvancedParameters'][
                'ThresholdingMethod'] == 'All':
                for num in range(1, NUM_RESIZING_METHOD_OPTIONS + 1):
                    self.dict_parameters_list.append(copy.deepcopy(self.dict_parameters))
                    self.dict_parameters_list[num - 1]['AdvancedParameters']['ThresholdingMethod'] = num

            if self.dict_parameters['AdvancedParameters']['ThresholdingMethod'] == 'All' and \
                    self.dict_parameters['AdvancedParameters'][
                        'ResizingMethod'] == 'All':
                for num in range(1, NUM_THRESHOLDING_METHOD_OPTIONS + 1):
                    for num_2 in range(1, NUM_RESIZING_METHOD_OPTIONS + 1):
                        self.dict_parameters_list.append(copy.deepcopy(self.dict_parameters))
                        self.dict_parameters_list[(num - 1) * NUM_RESIZING_METHOD_OPTIONS + num_2 - 1]['AdvancedParameters'][
                            'ThresholdingMethod'] = num
                        self.dict_parameters_list[(num - 1) * NUM_RESIZING_METHOD_OPTIONS + num_2 - 1]['AdvancedParameters'][
                            'ResizingMethod'] = num_2

            else:
                self.dict_parameters_list.append(copy.deepcopy(self.dict_parameters))

            df_output_total = pd.DataFrame(
                columns=['pdf_filename', 'sample_filename', 'txt_reference', 'ocr_output', 'cer', 'wer', 'resizing_method',
                         'thresholding_method'])
            num = 0
            for self.dict_parameters in self.dict_parameters_list:
                num += 1
                num_total = len(self.dict_parameters_list)
                self.progress.emit(num, num_total)
                print(self.dict_parameters)
                ScanBook = Scan(self.dict_parameters)
                df_output = ScanBook.run()
                df_output_total = pd.concat([df_output_total, df_output])
                cwd = os.getcwd()
                df_output_total.to_csv("C:/Users/Hp/PycharmProjects/ImageToTextArgentina/data/df_output.csv", index = False)
            df_output_total
            self.finished.emit()



    def runLongTask(self):
        # Step 2: Create a QThread object
        self.thread = QThread()
        # Step 3: Create a worker object
        self.worker = self.Worker(self.dict_parameters)
        # Step 4: Move worker to the thread
        self.worker.moveToThread(self.thread)
        # Step 5: Connect signals and slots
        self.thread.started.connect(self.worker.run)
        self.worker.finished.connect(self.thread.quit)
        self.worker.finished.connect(self.worker.deleteLater)
        self.thread.finished.connect(self.thread.deleteLater)
        self.worker.progress.connect(self.reportProgress)
        # Step 6: Start the thread
        self.thread.start()

        # Final resets
        self.pushButton.setEnabled(False)
        self.thread.finished.connect(
            lambda: self.pushButton.setEnabled(True)
        )
        self.thread.finished.connect(
            lambda: self.label.setText("Long-Running Step: 0")
        )

    class pandasModel(QAbstractTableModel):
        def __init__(self, data):
            QAbstractTableModel.__init__(self)
            self._data = data

        def rowCount(self, parent=None):
            return self._data.shape[0]

        def columnCount(self, parnet=None):
            return self._data.shape[1]

        def data(self, index, role=Qt.DisplayRole):
            if index.isValid():
                if role == Qt.DisplayRole:
                    return str(self._data.iloc[index.row(), index.column()])
            return None

        def headerData(self, col, orientation, role):
            if orientation == Qt.Horizontal and role == Qt.DisplayRole:
                return self._data.columns[col]
            return None

    # def run(self):
    #     sleep(4)

    def refresh(self):
        # self.df.replace([self.df['b'][0]], self.df['b'][0] + self.n, inplace=True)
        cwd = os.getcwd()
        self.df = pd.read_csv("C:/Users/Hp/PycharmProjects/ImageToTextArgentina/data/df_output.csv")
        model = self.pandasModel(self.df)
        self.tableView.setModel(model)
        header = self.tableView.horizontalHeader()
        for n in range(self.df.shape[1]):
            header.setSectionResizeMode(n, QHeaderView.Stretch)
        self.tableView.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Run"))
        self.pushButton_2.setText(_translate("MainWindow", "Refresh"))
        self.label.setText(_translate("MainWindow", "Click Run Button"))
        self.label.adjustSize()

if __name__ == "__main__":

    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Screen3()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
